# Generated by Django 5.2.5 on 2025-08-22 02:29

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserATM",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, null=True, verbose_name="telefono"),
                ),
                (
                    "address",
                    models.CharField(
                        max_length=500, null=True, verbose_name="direccion"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(null=True, verbose_name="fecha_de_nacimiento"),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(null=True, verbose_name="numero_de_cuenta"),
                ),
                ("balance", models.FloatField(default=0, verbose_name="balance")),
                (
                    "account_authenticated",
                    models.BooleanField(
                        default=False, verbose_name="cuenta_autenticada"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.useratm",
                        verbose_name="usuario",
                    ),
                ),
            ],
        ),
    ]
