# Generated by Django 5.2.5 on 2025-08-26 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField(verbose_name="value")),
                ("identity", models.CharField(max_length=30, verbose_name="identity")),
                (
                    "currency_code",
                    models.CharField(max_length=10, verbose_name="currency_code"),
                ),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="", verbose_name="image"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MachineAccountBills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0, verbose_name="quantity")),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="transactions.bill",
                        verbose_name="bill",
                    ),
                ),
                (
                    "machine_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.machineaccount",
                        verbose_name="machine_account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_created=True, verbose_name="creation_date"
                    ),
                ),
                (
                    "id",
                    models.IntegerField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="transaction_id",
                    ),
                ),
                (
                    "destiny_account_number",
                    models.CharField(
                        max_length=16, verbose_name="destiny_account_number"
                    ),
                ),
                ("amount", models.FloatField(default=0, verbose_name="amount")),
                (
                    "transaction_type",
                    models.TextField(
                        choices=[
                            ("N", "NonSelected"),
                            ("W", "withdraw"),
                            ("D", "deposit"),
                            ("T", "transfer"),
                        ],
                        default="NonSelected",
                        verbose_name="transaction_type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (1, "None"),
                            (2, "On going"),
                            (3, "Successful"),
                            (4, "Failed"),
                        ],
                        default="None",
                        verbose_name="status",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="description"
                    ),
                ),
                (
                    "origin_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                        verbose_name="origin_account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionBills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0, verbose_name="quantity")),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="transactions.bill",
                        verbose_name="bill",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transactions.transaction",
                        verbose_name="transaction",
                    ),
                ),
            ],
        ),
    ]
