# Generated by Django 5.2.1 on 2025-06-11 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField(verbose_name="valor")),
                ("identity", models.TextField(max_length=30, verbose_name="identidad")),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_created=True, null=True, verbose_name="fecha_de_creacion"
                    ),
                ),
                ("sum", models.IntegerField(verbose_name="monto")),
                (
                    "status",
                    models.CharField(
                        default="On going", max_length=100, verbose_name="estado"
                    ),
                ),
                (
                    "bills",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="transactions.bill",
                        verbose_name="billetes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionBills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(null=True, verbose_name="cantidad")),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="transactions.bill",
                        verbose_name="billete",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="transactions.transaction",
                        verbose_name="transaccion",
                    ),
                ),
            ],
        ),
    ]
