# Generated by Django 5.2.5 on 2025-08-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="destiny_account_number",
            field=models.CharField(
                max_length=16, null=True, verbose_name="destiny_account_number"
            ),
        ),
    ]
