# Generated by Django 5.2.5 on 2025-08-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_alter_transaction_destiny_account_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="id",
            field=models.IntegerField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="transaction_id",
            ),
        ),
    ]
