# Generated by Django 5.2.5 on 2025-08-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_alter_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation_date"),
        ),
    ]
