# Generated by Django 5.2.5 on 2025-08-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_alter_transaction_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    (1, "None"),
                    (2, "On going"),
                    (3, "Successful"),
                    (4, "Cancelled"),
                    (5, "Failed"),
                ],
                default="None",
                verbose_name="status",
            ),
        ),
    ]
