# Generated by Django 5.2.5 on 2025-09-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_alter_transaction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="destiny_account_number",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                verbose_name="destiny_account_number",
            ),
        ),
    ]
