# Generated by Django 5.2.5 on 2025-09-16 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("transactions", "0006_alter_transaction_destiny_account_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="static/bills", verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="machineaccountbills",
            name="machine_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="machine_account_bills",
                to="accounts.machineaccount",
                verbose_name="machine_account",
            ),
        ),
    ]
