# Generated by Django 5.2.5 on 2025-09-16 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0007_alter_bill_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionbills",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_bills",
                to="transactions.transaction",
                verbose_name="transaction",
            ),
        ),
    ]
