# Generated by Django 5.2.5 on 2025-09-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0008_alter_transactionbills_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="machineaccountbills",
            name="total_value",
            field=models.FloatField(default=0, verbose_name="total_value"),
        ),
    ]
