# Generated by Django 5.2.5 on 2025-09-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0009_machineaccountbills_total_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionbills",
            name="total_value",
            field=models.FloatField(default=0, verbose_name="total_value"),
        ),
    ]
